[package]
name = "rsock"
version = "0.1.0"
authors = ["Hrafnskogr <hrafnskogr@pm.me"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
